### ISSUE TITLE
Discord nogo

### ISSUE THREAD

**Issue by baqwas** [OndraGejdos/OG-star-tracker-#2]
Hello @OndraGejdos,

Since my use of Discord is fairly trivial and minimal, I couldn't locate your channel. Let me know when you are ready to ship with more details via baqwas at yahoo dot com. Thanks again for a wonderful and appealing project.

Regards.

**Comment by OndraGejdos** [comment]
https://discord.gg/pU2KmB5a . Info on github is little bit outdated new stls are on printables i have updated few things.  I will update the info. I am always happy when somebody download my project or say he wants to build one. every single time

**Comment by baqwas** [comment]
Thanks.
