### ISSUE TITLE
STEP File Import Error

### ISSUE THREAD

**Issue by baqwas** [OndraGejdos/OG-star-tracker-#3]
Hello @OndraGejdos,

I tried to import your STEP file into OnShape (which is the only one that I have access to for modeling purposes). The import process reported that:

`hlavní část nová contains faulty topology`

Just feedback for your review; I don't know much about these things so I don't consider it as an issue but simply wanted to let you know.

Regards.

**Comment by OndraGejdos** [comment]
You might want to try improrting stl or using fusion 360

**Comment by baqwas** [comment]
Will do. Thanks.
